### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Planeflyer11**
eepic
eepic

### CODE REVIEW

**Comment by Planeflyer11** [comment]
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
eepic
v

**Comment by proJM-Coding** [comment]
yes

**Review by proJM-Coding — APPROVED** [review]
Good

**Comment by proJM-Coding** [comment]
do it

**Comment by proJM-Coding** [comment]
This is already added why?

**Comment by proJM-Coding** [comment]
also

**Comment by proJM-Coding** [comment]
eepic

**Pull request merged**
